Implement Persistence
free-explorers/veshell-prototype pull request #24
Opened 2024-02-22 21:59 UTC by PapyElGringo

# Persistence

First approach of the persistence where configurations of Screens, Workspace and Windows are automatically saved locally and restored at initialization.

## JSON Approach

Currently every states are saved at `$XDG_CONFIG_HOME/veshell/persistence/{model}/{uuid}.json`

2024-02-24 15:04 UTC, roscale requested changes
Hmm, I get this error when I start the compositor.

```
flutter: AsyncError<Map<String, Map<String, Map<String, dynamic>>>>(error: Null check operator used on a null value, stackTrace: #0      persistenceDirectory (package:shell/shared/persistence/persistence_manager.dart:8)
#1      PersistenceManager.loadAllModelsJson (package:shell/shared/persistence/persistence_manager.dart)
#2      PersistentJsonByFolder.build (package:shell/shared/provider/persistent_json_by_folder.dart:10)
```

2024-02-24 15:04 UTC, roscale commented on shell/lib/shared/persistence/persistence_manager.dart
> +    if (!persistentFolder.existsSync()) {
Is there a reason you used the sync variant instead of the async one?
Same question for the other ones below.

2024-02-24 15:25 UTC, PapyElGringo commented on shell/lib/shared/persistence/persistence_manager.dart
> +    if (!persistentFolder.existsSync()) {
Using async I had a warning about it https://dart.dev/tools/linter-rules/avoid_slow_async_io

2024-02-24 15:26 UTC, PapyElGringo commented
> Hmm, I get this error when I start the compositor.
> 
> ```
> flutter: AsyncError<Map<String, Map<String, Map<String, dynamic>>>>(error: Null check operator used on a null value, stackTrace:
> #0      persistenceDirectory (package:shell/shared/persistence/persistence_manager.dart:8)
> #1      PersistenceManager.loadAllModelsJson (package:shell/shared/persistence/persistence_manager.dart)
> #2      PersistentJsonByFolder.build (package:shell/shared/provider/persistent_json_by_folder.dart:10)
> ```

I guess you don't have **Platform.environment['XDG_CONFIG_HOME']** variable set?

2024-02-24 15:32 UTC, roscale commented
You're right, I don't have `XDG_CONFIG_HOME` set.

2024-02-24 15:35 UTC, roscale commented
You can probably default to `$HOME/.config` in case this environment variable is not set. I think that `HOME` will be always available.

2024-02-24 18:51 UTC, roscale commented on shell/lib/shared/persistence/persistence_manager.dart
> +    if (!persistentFolder.existsSync()) {
Oh wow, I didn't even know about this. I wonder why this is the case though. Maybe obtaining this information is so fast that involving the asynchronous runtime is slower than just calling the sync function. Nonetheless, very interesting.

2024-03-17 11:49 UTC, roscale approved these changes

2024-03-17 12:47 UTC, merged